# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/probe_calibration_wizard.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 963)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(500, 750))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_fileManagement = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_fileManagement.setObjectName("groupBox_fileManagement")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_fileManagement)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox_fileManagement)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.lineEdit_saveLocation = QtWidgets.QLineEdit(self.groupBox_fileManagement)
        self.lineEdit_saveLocation.setObjectName("lineEdit_saveLocation")
        self.horizontalLayout.addWidget(self.lineEdit_saveLocation)
        self.pushButton_chooseSaveLocation = QtWidgets.QPushButton(self.groupBox_fileManagement)
        self.pushButton_chooseSaveLocation.setObjectName("pushButton_chooseSaveLocation")
        self.horizontalLayout.addWidget(self.pushButton_chooseSaveLocation)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_load = QtWidgets.QPushButton(self.groupBox_fileManagement)
        self.pushButton_load.setObjectName("pushButton_load")
        self.horizontalLayout_2.addWidget(self.pushButton_load)
        self.pushButton_saveAs = QtWidgets.QPushButton(self.groupBox_fileManagement)
        self.pushButton_saveAs.setObjectName("pushButton_saveAs")
        self.horizontalLayout_2.addWidget(self.pushButton_saveAs)
        self.pushButton_save = QtWidgets.QPushButton(self.groupBox_fileManagement)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_2.addWidget(self.pushButton_save)
        self.checkBox_zmq = QtWidgets.QCheckBox(self.groupBox_fileManagement)
        self.checkBox_zmq.setMaximumSize(QtCore.QSize(150, 16777215))
        self.checkBox_zmq.setChecked(False)
        self.checkBox_zmq.setObjectName("checkBox_zmq")
        self.horizontalLayout_2.addWidget(self.checkBox_zmq)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.groupBox_fileManagement)
        self.groupBox_probeViewer = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_probeViewer.setObjectName("groupBox_probeViewer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_probeViewer)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox_probeViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_3.addWidget(self.graphicsView)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_real = QtWidgets.QRadioButton(self.groupBox_probeViewer)
        self.radioButton_real.setChecked(True)
        self.radioButton_real.setObjectName("radioButton_real")
        self.buttonGroup_realVsFourier = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_realVsFourier.setObjectName("buttonGroup_realVsFourier")
        self.buttonGroup_realVsFourier.addButton(self.radioButton_real)
        self.horizontalLayout_4.addWidget(self.radioButton_real)
        self.radioButton_fourier = QtWidgets.QRadioButton(self.groupBox_probeViewer)
        self.radioButton_fourier.setObjectName("radioButton_fourier")
        self.buttonGroup_realVsFourier.addButton(self.radioButton_fourier)
        self.horizontalLayout_4.addWidget(self.radioButton_fourier)
        self.line = QtWidgets.QFrame(self.groupBox_probeViewer)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.radioButton_amplitude = QtWidgets.QRadioButton(self.groupBox_probeViewer)
        self.radioButton_amplitude.setChecked(True)
        self.radioButton_amplitude.setObjectName("radioButton_amplitude")
        self.buttonGroup_amplitudeVsPhase = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_amplitudeVsPhase.setObjectName("buttonGroup_amplitudeVsPhase")
        self.buttonGroup_amplitudeVsPhase.addButton(self.radioButton_amplitude)
        self.horizontalLayout_4.addWidget(self.radioButton_amplitude)
        self.radioButton_phase = QtWidgets.QRadioButton(self.groupBox_probeViewer)
        self.radioButton_phase.setObjectName("radioButton_phase")
        self.buttonGroup_amplitudeVsPhase.addButton(self.radioButton_phase)
        self.horizontalLayout_4.addWidget(self.radioButton_phase)
        self.line_2 = QtWidgets.QFrame(self.groupBox_probeViewer)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_4.addWidget(self.line_2)
        self.label_7 = QtWidgets.QLabel(self.groupBox_probeViewer)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.spinBox_viewMode = QtWidgets.QSpinBox(self.groupBox_probeViewer)
        self.spinBox_viewMode.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinBox_viewMode.setMinimum(1)
        self.spinBox_viewMode.setMaximum(10)
        self.spinBox_viewMode.setObjectName("spinBox_viewMode")
        self.horizontalLayout_4.addWidget(self.spinBox_viewMode)
        self.label_nmodeReadout = QtWidgets.QLabel(self.groupBox_probeViewer)
        self.label_nmodeReadout.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_nmodeReadout.setObjectName("label_nmodeReadout")
        self.horizontalLayout_4.addWidget(self.label_nmodeReadout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addWidget(self.groupBox_probeViewer)
        self.groupBox_probeAdjustment = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_probeAdjustment.setObjectName("groupBox_probeAdjustment")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_probeAdjustment)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.groupBox_probeAdjustment)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.spinBox_nmodes = QtWidgets.QSpinBox(self.groupBox_probeAdjustment)
        self.spinBox_nmodes.setMinimum(1)
        self.spinBox_nmodes.setMaximum(10)
        self.spinBox_nmodes.setProperty("value", 10)
        self.spinBox_nmodes.setObjectName("spinBox_nmodes")
        self.horizontalLayout_5.addWidget(self.spinBox_nmodes)
        self.horizontalSlider_nmodes = QtWidgets.QSlider(self.groupBox_probeAdjustment)
        self.horizontalSlider_nmodes.setMinimum(1)
        self.horizontalSlider_nmodes.setMaximum(10)
        self.horizontalSlider_nmodes.setSliderPosition(10)
        self.horizontalSlider_nmodes.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_nmodes.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_nmodes.setTickInterval(1)
        self.horizontalSlider_nmodes.setObjectName("horizontalSlider_nmodes")
        self.horizontalLayout_5.addWidget(self.horizontalSlider_nmodes)
        self.checkBox_ortho = QtWidgets.QCheckBox(self.groupBox_probeAdjustment)
        self.checkBox_ortho.setObjectName("checkBox_ortho")
        self.horizontalLayout_5.addWidget(self.checkBox_ortho)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_dzMax = QtWidgets.QLineEdit(self.groupBox_probeAdjustment)
        self.lineEdit_dzMax.setMaximumSize(QtCore.QSize(52, 16777215))
        self.lineEdit_dzMax.setObjectName("lineEdit_dzMax")
        self.gridLayout.addWidget(self.lineEdit_dzMax, 0, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_probeAdjustment)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_eMin = QtWidgets.QLineEdit(self.groupBox_probeAdjustment)
        self.lineEdit_eMin.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_eMin.setReadOnly(False)
        self.lineEdit_eMin.setObjectName("lineEdit_eMin")
        self.gridLayout.addWidget(self.lineEdit_eMin, 2, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_probeAdjustment)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.comboBox_eUnits = QtWidgets.QComboBox(self.groupBox_probeAdjustment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_eUnits.sizePolicy().hasHeightForWidth())
        self.comboBox_eUnits.setSizePolicy(sizePolicy)
        self.comboBox_eUnits.setMinimumSize(QtCore.QSize(55, 0))
        self.comboBox_eUnits.setMaximumSize(QtCore.QSize(55, 16777215))
        self.comboBox_eUnits.setObjectName("comboBox_eUnits")
        self.comboBox_eUnits.addItem("")
        self.comboBox_eUnits.addItem("")
        self.comboBox_eUnits.addItem("")
        self.comboBox_eUnits.addItem("")
        self.comboBox_eUnits.addItem("")
        self.gridLayout.addWidget(self.comboBox_eUnits, 2, 6, 1, 1)
        self.lineEdit_dzMin = QtWidgets.QLineEdit(self.groupBox_probeAdjustment)
        self.lineEdit_dzMin.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_dzMin.setObjectName("lineEdit_dzMin")
        self.gridLayout.addWidget(self.lineEdit_dzMin, 0, 3, 1, 1)
        self.horizontalSlider_e = QtWidgets.QSlider(self.groupBox_probeAdjustment)
        self.horizontalSlider_e.setMaximum(2000)
        self.horizontalSlider_e.setProperty("value", 1000)
        self.horizontalSlider_e.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_e.setObjectName("horizontalSlider_e")
        self.gridLayout.addWidget(self.horizontalSlider_e, 2, 4, 1, 1)
        self.comboBox_dzUnits = QtWidgets.QComboBox(self.groupBox_probeAdjustment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_dzUnits.sizePolicy().hasHeightForWidth())
        self.comboBox_dzUnits.setSizePolicy(sizePolicy)
        self.comboBox_dzUnits.setMinimumSize(QtCore.QSize(55, 0))
        self.comboBox_dzUnits.setMaximumSize(QtCore.QSize(55, 16777215))
        self.comboBox_dzUnits.setObjectName("comboBox_dzUnits")
        self.comboBox_dzUnits.addItem("")
        self.comboBox_dzUnits.addItem("")
        self.comboBox_dzUnits.addItem("")
        self.comboBox_dzUnits.addItem("")
        self.comboBox_dzUnits.addItem("")
        self.gridLayout.addWidget(self.comboBox_dzUnits, 0, 6, 1, 1)
        self.lineEdit_eMax = QtWidgets.QLineEdit(self.groupBox_probeAdjustment)
        self.lineEdit_eMax.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_eMax.setReadOnly(False)
        self.lineEdit_eMax.setObjectName("lineEdit_eMax")
        self.gridLayout.addWidget(self.lineEdit_eMax, 2, 5, 1, 1)
        self.pushButton_dzReset = QtWidgets.QPushButton(self.groupBox_probeAdjustment)
        self.pushButton_dzReset.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_dzReset.setObjectName("pushButton_dzReset")
        self.gridLayout.addWidget(self.pushButton_dzReset, 0, 7, 1, 1)
        self.pushButton_eReset = QtWidgets.QPushButton(self.groupBox_probeAdjustment)
        self.pushButton_eReset.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_eReset.setObjectName("pushButton_eReset")
        self.gridLayout.addWidget(self.pushButton_eReset, 2, 7, 1, 1)
        self.horizontalSlider_dz = QtWidgets.QSlider(self.groupBox_probeAdjustment)
        self.horizontalSlider_dz.setMinimum(-200)
        self.horizontalSlider_dz.setMaximum(200)
        self.horizontalSlider_dz.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dz.setObjectName("horizontalSlider_dz")
        self.gridLayout.addWidget(self.horizontalSlider_dz, 0, 4, 1, 1)
        self.lineEdit_dz = QtWidgets.QLineEdit(self.groupBox_probeAdjustment)
        self.lineEdit_dz.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_dz.setObjectName("lineEdit_dz")
        self.gridLayout.addWidget(self.lineEdit_dz, 0, 1, 1, 1)
        self.lineEdit_e = QtWidgets.QLineEdit(self.groupBox_probeAdjustment)
        self.lineEdit_e.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_e.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_e.setReadOnly(False)
        self.lineEdit_e.setObjectName("lineEdit_e")
        self.gridLayout.addWidget(self.lineEdit_e, 2, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.groupBox_probeAdjustment)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 0, 2, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.groupBox_probeAdjustment)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 2, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.checkBox_updateDzWithE = QtWidgets.QCheckBox(self.groupBox_probeAdjustment)
        self.checkBox_updateDzWithE.setStyleSheet("")
        self.checkBox_updateDzWithE.setObjectName("checkBox_updateDzWithE")
        self.verticalLayout_4.addWidget(self.checkBox_updateDzWithE, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.groupBox_probeAdjustment)
        self.groupBox_calibrationHints = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_calibrationHints.setObjectName("groupBox_calibrationHints")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_calibrationHints)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_calibrationHints)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.comboBox_energyCorrectionPlan = QtWidgets.QComboBox(self.groupBox_calibrationHints)
        self.comboBox_energyCorrectionPlan.setMinimumSize(QtCore.QSize(130, 0))
        self.comboBox_energyCorrectionPlan.setObjectName("comboBox_energyCorrectionPlan")
        self.comboBox_energyCorrectionPlan.addItem("")
        self.comboBox_energyCorrectionPlan.addItem("")
        self.comboBox_energyCorrectionPlan.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_energyCorrectionPlan)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(self.groupBox_calibrationHints)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lineEdit_a0 = QtWidgets.QLineEdit(self.groupBox_calibrationHints)
        self.lineEdit_a0.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_a0.setObjectName("lineEdit_a0")
        self.horizontalLayout_3.addWidget(self.lineEdit_a0)
        self.comboBox_a0Units = QtWidgets.QComboBox(self.groupBox_calibrationHints)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_a0Units.sizePolicy().hasHeightForWidth())
        self.comboBox_a0Units.setSizePolicy(sizePolicy)
        self.comboBox_a0Units.setMaximumSize(QtCore.QSize(50, 16777215))
        self.comboBox_a0Units.setObjectName("comboBox_a0Units")
        self.comboBox_a0Units.addItem("")
        self.comboBox_a0Units.addItem("")
        self.comboBox_a0Units.addItem("")
        self.comboBox_a0Units.addItem("")
        self.comboBox_a0Units.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_a0Units)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_includeBackground = QtWidgets.QCheckBox(self.groupBox_calibrationHints)
        self.checkBox_includeBackground.setChecked(True)
        self.checkBox_includeBackground.setObjectName("checkBox_includeBackground")
        self.horizontalLayout_6.addWidget(self.checkBox_includeBackground)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.pushButton_viewBackground = QtWidgets.QPushButton(self.groupBox_calibrationHints)
        self.pushButton_viewBackground.setMinimumSize(QtCore.QSize(130, 0))
        self.pushButton_viewBackground.setObjectName("pushButton_viewBackground")
        self.horizontalLayout_6.addWidget(self.pushButton_viewBackground)
        self.pushButton_loadBackground = QtWidgets.QPushButton(self.groupBox_calibrationHints)
        self.pushButton_loadBackground.setMinimumSize(QtCore.QSize(130, 0))
        self.pushButton_loadBackground.setObjectName("pushButton_loadBackground")
        self.horizontalLayout_6.addWidget(self.pushButton_loadBackground)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBox_includeMask = QtWidgets.QCheckBox(self.groupBox_calibrationHints)
        self.checkBox_includeMask.setChecked(True)
        self.checkBox_includeMask.setObjectName("checkBox_includeMask")
        self.horizontalLayout_7.addWidget(self.checkBox_includeMask)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.pushButton_viewMask = QtWidgets.QPushButton(self.groupBox_calibrationHints)
        self.pushButton_viewMask.setMinimumSize(QtCore.QSize(130, 0))
        self.pushButton_viewMask.setObjectName("pushButton_viewMask")
        self.horizontalLayout_7.addWidget(self.pushButton_viewMask)
        self.pushButton_loadMask = QtWidgets.QPushButton(self.groupBox_calibrationHints)
        self.pushButton_loadMask.setMinimumSize(QtCore.QSize(130, 0))
        self.pushButton_loadMask.setObjectName("pushButton_loadMask")
        self.horizontalLayout_7.addWidget(self.pushButton_loadMask)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addWidget(self.groupBox_calibrationHints)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label_8.setBuddy(self.spinBox_nmodes)
        self.label.setBuddy(self.lineEdit_dz)
        self.label_2.setBuddy(self.lineEdit_e)
        self.label_4.setBuddy(self.lineEdit_a0)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_saveLocation, self.pushButton_chooseSaveLocation)
        MainWindow.setTabOrder(self.pushButton_chooseSaveLocation, self.pushButton_load)
        MainWindow.setTabOrder(self.pushButton_load, self.pushButton_saveAs)
        MainWindow.setTabOrder(self.pushButton_saveAs, self.pushButton_save)
        MainWindow.setTabOrder(self.pushButton_save, self.checkBox_zmq)
        MainWindow.setTabOrder(self.checkBox_zmq, self.graphicsView)
        MainWindow.setTabOrder(self.graphicsView, self.radioButton_real)
        MainWindow.setTabOrder(self.radioButton_real, self.radioButton_fourier)
        MainWindow.setTabOrder(self.radioButton_fourier, self.radioButton_amplitude)
        MainWindow.setTabOrder(self.radioButton_amplitude, self.radioButton_phase)
        MainWindow.setTabOrder(self.radioButton_phase, self.spinBox_viewMode)
        MainWindow.setTabOrder(self.spinBox_viewMode, self.spinBox_nmodes)
        MainWindow.setTabOrder(self.spinBox_nmodes, self.horizontalSlider_nmodes)
        MainWindow.setTabOrder(self.horizontalSlider_nmodes, self.checkBox_ortho)
        MainWindow.setTabOrder(self.checkBox_ortho, self.lineEdit_dz)
        MainWindow.setTabOrder(self.lineEdit_dz, self.lineEdit_dzMin)
        MainWindow.setTabOrder(self.lineEdit_dzMin, self.horizontalSlider_dz)
        MainWindow.setTabOrder(self.horizontalSlider_dz, self.lineEdit_dzMax)
        MainWindow.setTabOrder(self.lineEdit_dzMax, self.comboBox_dzUnits)
        MainWindow.setTabOrder(self.comboBox_dzUnits, self.pushButton_dzReset)
        MainWindow.setTabOrder(self.pushButton_dzReset, self.lineEdit_e)
        MainWindow.setTabOrder(self.lineEdit_e, self.lineEdit_eMin)
        MainWindow.setTabOrder(self.lineEdit_eMin, self.horizontalSlider_e)
        MainWindow.setTabOrder(self.horizontalSlider_e, self.lineEdit_eMax)
        MainWindow.setTabOrder(self.lineEdit_eMax, self.comboBox_eUnits)
        MainWindow.setTabOrder(self.comboBox_eUnits, self.pushButton_eReset)
        MainWindow.setTabOrder(self.pushButton_eReset, self.checkBox_updateDzWithE)
        MainWindow.setTabOrder(self.checkBox_updateDzWithE, self.comboBox_energyCorrectionPlan)
        MainWindow.setTabOrder(self.comboBox_energyCorrectionPlan, self.lineEdit_a0)
        MainWindow.setTabOrder(self.lineEdit_a0, self.comboBox_a0Units)
        MainWindow.setTabOrder(self.comboBox_a0Units, self.checkBox_includeBackground)
        MainWindow.setTabOrder(self.checkBox_includeBackground, self.pushButton_viewBackground)
        MainWindow.setTabOrder(self.pushButton_viewBackground, self.pushButton_loadBackground)
        MainWindow.setTabOrder(self.pushButton_loadBackground, self.checkBox_includeMask)
        MainWindow.setTabOrder(self.checkBox_includeMask, self.pushButton_viewMask)
        MainWindow.setTabOrder(self.pushButton_viewMask, self.pushButton_loadMask)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Probe Calibration Wizard Seven Thousand Twelve"))
        self.groupBox_fileManagement.setTitle(_translate("MainWindow", "File Management"))
        self.label_5.setText(_translate("MainWindow", "Save Location:"))
        self.pushButton_chooseSaveLocation.setText(_translate("MainWindow", "Choose..."))
        self.pushButton_load.setText(_translate("MainWindow", "Load..."))
        self.pushButton_saveAs.setText(_translate("MainWindow", "Save As..."))
        self.pushButton_save.setText(_translate("MainWindow", "Save"))
        self.checkBox_zmq.setText(_translate("MainWindow", "Broadcast over ØMQ"))
        self.groupBox_probeViewer.setTitle(_translate("MainWindow", "Probe Viewer"))
        self.radioButton_real.setText(_translate("MainWindow", "&Real"))
        self.radioButton_fourier.setText(_translate("MainWindow", "&Fourier"))
        self.radioButton_amplitude.setText(_translate("MainWindow", "&Amplitude"))
        self.radioButton_phase.setText(_translate("MainWindow", "&Phase"))
        self.label_7.setText(_translate("MainWindow", "Mode:"))
        self.label_nmodeReadout.setText(_translate("MainWindow", "/10"))
        self.groupBox_probeAdjustment.setTitle(_translate("MainWindow", "Probe Adjustment"))
        self.label_8.setText(_translate("MainWindow", "# of &Modes:"))
        self.checkBox_ortho.setText(_translate("MainWindow", "Orthogonalize"))
        self.lineEdit_dzMax.setText(_translate("MainWindow", "200"))
        self.label.setText(_translate("MainWindow", "Δ&Z:"))
        self.lineEdit_eMin.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "&E:"))
        self.comboBox_eUnits.setCurrentText(_translate("MainWindow", "meV"))
        self.comboBox_eUnits.setItemText(0, _translate("MainWindow", "ueV"))
        self.comboBox_eUnits.setItemText(1, _translate("MainWindow", "meV"))
        self.comboBox_eUnits.setItemText(2, _translate("MainWindow", "eV"))
        self.comboBox_eUnits.setItemText(3, _translate("MainWindow", "keV"))
        self.comboBox_eUnits.setItemText(4, _translate("MainWindow", "MeV"))
        self.lineEdit_dzMin.setText(_translate("MainWindow", "-200"))
        self.comboBox_dzUnits.setItemText(0, _translate("MainWindow", "nm"))
        self.comboBox_dzUnits.setItemText(1, _translate("MainWindow", "um"))
        self.comboBox_dzUnits.setItemText(2, _translate("MainWindow", "mm"))
        self.comboBox_dzUnits.setItemText(3, _translate("MainWindow", "cm"))
        self.comboBox_dzUnits.setItemText(4, _translate("MainWindow", "m"))
        self.lineEdit_eMax.setText(_translate("MainWindow", "2000"))
        self.pushButton_dzReset.setText(_translate("MainWindow", "Reset"))
        self.pushButton_eReset.setText(_translate("MainWindow", "Reset"))
        self.lineEdit_dz.setText(_translate("MainWindow", "0"))
        self.lineEdit_e.setText(_translate("MainWindow", "1000"))
        self.checkBox_updateDzWithE.setText(_translate("MainWindow", "Update ΔZ with E to simulate chromatic aberration"))
        self.groupBox_calibrationHints.setTitle(_translate("MainWindow", "Calibration Hints && Additional Information"))
        self.label_3.setText(_translate("MainWindow", "Energy Correction Plan:"))
        self.comboBox_energyCorrectionPlan.setItemText(0, _translate("MainWindow", "Assume Fixed ZP"))
        self.comboBox_energyCorrectionPlan.setItemText(1, _translate("MainWindow", "None"))
        self.comboBox_energyCorrectionPlan.setItemText(2, _translate("MainWindow", "Stay In Focus"))
        self.label_4.setText(_translate("MainWindow", "&A0:"))
        self.comboBox_a0Units.setCurrentText(_translate("MainWindow", "nm"))
        self.comboBox_a0Units.setItemText(0, _translate("MainWindow", "nm"))
        self.comboBox_a0Units.setItemText(1, _translate("MainWindow", "um"))
        self.comboBox_a0Units.setItemText(2, _translate("MainWindow", "mm"))
        self.comboBox_a0Units.setItemText(3, _translate("MainWindow", "cm"))
        self.comboBox_a0Units.setItemText(4, _translate("MainWindow", "m"))
        self.checkBox_includeBackground.setText(_translate("MainWindow", "Include Background"))
        self.pushButton_viewBackground.setText(_translate("MainWindow", "View Background..."))
        self.pushButton_loadBackground.setText(_translate("MainWindow", "Load Background..."))
        self.checkBox_includeMask.setText(_translate("MainWindow", "Include Mask"))
        self.pushButton_viewMask.setText(_translate("MainWindow", "View Mask..."))
        self.pushButton_loadMask.setText(_translate("MainWindow", "Load Mask..."))

